# Generated by Django 5.2 on 2025-10-04 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('overview', models.TextField(blank=True, help_text='Detailed course overview', null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon symbol', max_length=10, null=True)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('marketing', 'Marketing'), ('design', 'Design'), ('data', 'Data'), ('music', 'Music'), ('creative', 'Creative'), ('lifestyle', 'Lifestyle'), ('language', 'Language'), ('health', 'Health')], default='creative', max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('students', models.CharField(default=0, help_text='e.g. 12.5k, 5.4k', max_length=50)),
                ('duration', models.CharField(help_text='e.g. 3-6 months', max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('color', models.CharField(choices=[('Blue and Purple', 'from-blue-500 to-purple-600'), ('Green and teal', 'from-green-500 to-teal-600'), ('Yellow and Orange', 'from-yellow-500 to-orange-600'), ('Amber and Orange', 'from-amber-500 to-orange-600'), ('Pink and Rose', 'from-pink-500 to-rose-600'), ('Pink and Red', 'from-pink-500 to-red-600'), ('Purple and Indigo', 'from-purple-500 to-indigo-600'), ('Cyan and Blue', 'from-cyan-500 to-blue-600'), ('Indigo and Blue', 'from-indigo-500 to-blue-600'), ('Orange and Red', 'from-orange-500 to-red-600'), ('Emerald and Green', 'from-emerald-500 to-green-600'), ('Red and Pink', 'from-red-500 to-pink-600')], default='Blue and Purple', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('has_paths', models.BooleanField(default=True)),
                ('path_count', models.PositiveIntegerField(default=0)),
                ('special_features', models.JSONField(blank=True, default=list)),
                ('career_opportunities', models.JSONField(blank=True, default=list, help_text='List of possible careers')),
                ('tools_needed', models.JSONField(blank=True, default=list, help_text='Tools required for the course')),
                ('paths', models.JSONField(blank=True, default=list, help_text='Different learning paths (frontend, backend, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
