# Generated by Django 5.0.6 on 2025-08-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_created_at_skill_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
