# Generated by Django 5.2 on 2025-10-07 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='roadmap_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('micro_desc', models.CharField(max_length=255)),
                ('duration', models.CharField(help_text='e.g. 2–3 weeks', max_length=50)),
                ('sub_map_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='skills.path')),
            ],
        ),
    ]
