# Generated by Django 5.2 on 2025-10-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_path_roadmap_count_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecard',
            name='color',
            field=models.CharField(choices=[('from-blue-500 to-purple-600', 'Blue and Purple'), ('from-green-500 to-teal-600', 'Green and teal'), ('from-yellow-500 to-orange-600', 'Yellow and Orange'), ('from-amber-500 to-orange-600', 'Amber and Orange'), ('from-pink-500 to-rose-600', 'Pink and Rose'), ('from-pink-500 to-red-600', 'Pink and Red'), ('from-purple-500 to-indigo-600', 'Purple and Indigo'), ('from-cyan-500 to-blue-600', 'Cyan and Blue'), ('from-indigo-500 to-blue-600', 'Indigo and Blue'), ('from-orange-500 to-red-600', 'Orange and Red'), ('from-emerald-500 to-green-600', 'Emerald and Green'), ('from-red-500 to-pink-600', 'Red and Pink')], default='Blue and Purple'),
        ),
    ]
