# Generated by Django 5.2 on 2025-10-08 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_submap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('oneshot_vid_link', models.URLField(blank=True, null=True)),
                ('playlist_link', models.URLField(blank=True, null=True)),
                ('docs_link', models.URLField(blank=True, null=True)),
                ('pdf_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sub_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skills.submap')),
            ],
        ),
    ]
