# Generated by Django 5.2 on 2025-10-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='docs_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='oneshot_vid_link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='pdf_link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='playlist_link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='video_link',
        ),
        migrations.AddField(
            model_name='resource',
            name='link_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Playlist', 'Playlist'), ('One-Shot', 'One-Shot'), ('Web-Docs', 'Web-Docs'), ('PDF', 'PDF')], default='Video', max_length=20),
        ),
    ]
