# Generated by Django 5.2 on 2025-10-08 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_rename_docs_link_resource_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='path',
            name='roadmap_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
