# Generated by Django 5.2 on 2025-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_path_created_at_alter_path_roadmap_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='path',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='submap',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='sub_map_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='submap',
            name='resources_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
