# Generated by Django 5.2 on 2025-10-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_rename_time_path_duration_remove_path_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi')], default='English', max_length=20),
        ),
    ]
