# Generated by Django 5.2 on 2025-10-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_resource_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submap',
            name='micro_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla'), ('Hindi', 'Hindi')], default='English', max_length=20),
        ),
    ]
