# Generated by Django 6.0.2 on 2026-02-14 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_quiz_and_stage_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('questions_json', models.JSONField(help_text='List of {question_text, options, correct_index}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='skills.roadmap')),
            ],
        ),
    ]
