# Generated by Django 6.0.2 on 2026-02-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_quiz_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizSession',
            new_name='ExamSession',
        ),
    ]
