# Generated by Django 6.0.2 on 2026-02-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_usercoursetracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='questions_json',
            field=models.JSONField(help_text='List of {type, question_text, options?, correct_index?, expected_keywords?}'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='skills.roadmap'),
        ),
    ]
